# conda env create -f environment.yml
name: lklcom
channels:
    - conda-forge
    - menpo
dependencies:
    - python>=3.8
    - matplotlib
    - numpy>=1.15.0
    - scipy
    - pandas
    - pyyaml
    - pytables
