# conda env create -f environment.yml
name: lklcom
channels:
    - conda-forge
    - menpo
dependencies:
    - python
    - matplotlib
    - numpy
    - scipy
    - pandas
    - pyyaml
    - pytables
