package:
  name: likelihood_combiner
  version: "0.4.0"

source:
  git_url: https://github.com/TjarkMiener/likelihood_combiner
  git_rev: v0.4.0

build:
  number: 0

requirements:
  build:
    - python        
    - matplotlib
    - numpy
    - scipy
    - pandas
    - pyyaml
    - pytables
  host:
    - python
    - matplotlib
    - numpy
    - scipy
    - pandas
    - pyyaml
    - pytables
  run:
    - python
    - matplotlib
    - numpy
    - scipy
    - pandas
    - pyyaml
    - pytables
  test:
    imports:
      - likelihood_combiner

about:
  home: https://github.com/TjarkMiener/likelihood_combiner
  license: GPL-3.0 License
  license_file: LICENSE
  summary: LikelihoodCombiner combines likelihoods from different experiments.
extra:
  recipe-maintainers:
    - TjarkMiener
    - nietootein
