package:
  name: likelihood_combiner
  version: {{ environ['VERSION'] }}

source:
  git_url: https://github.com/TjarkMiener/likelihood_combiner

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
   - VERSION
   - CONDA_BLD_PATH

requirements:
  build:
    - python
    - matplotlib
    - numpy>=1.15.0
    - scipy
    - pandas
    - pyyaml
    - pytables
  host:
    - python
    - matplotlib
    - numpy>=1.15.0
    - scipy
    - pandas
    - pyyaml
    - pytables
  run:
    - python
    - matplotlib
    - numpy>=1.15.0
    - scipy
    - pandas
    - pyyaml
    - pytables
  test:
    imports:
      - likelihood_combiner

about:
  home: https://github.com/TjarkMiener/likelihood_combiner
  license: GPL-3.0 License
  license_file: LICENSE
  summary: LikelihoodCombiner combines likelihoods from different experiments.
extra:
  recipe-maintainers:
    - TjarkMiener
    - nietootein
