package:
  name: lklcom
  version: {{ environ['VERSION'] }}

source:
  git_url: https://github.com/TjarkMiener/likelihood_combiner

build:
  script_env:
   - VERSION
   - CONDA_BLD_PATH

about:
  home: https://github.com/TjarkMiener/likelihood_combiner
  license: GPL-3.0 License
  license_file: LICENSE
  summary: LikelihoodCombiner combines likelihoods from different experiments.
extra:
  recipe-maintainers:
    - TjarkMiener
    - nietootein
