package:
  name: likelihood_combiner
  version: "0.5.2"

source:
  git_url: https://github.com/TjarkMiener/likelihood_combiner
  git_rev: v0.5.2

build:
  noarch: generic
  number: 0

requirements:
  build:
    - python>=3.9
    - matplotlib
    - numpy>=1.15.0
    - scipy
    - pandas
    - pyyaml
    - pytables
  host:
    - python>=3.9
    - matplotlib
    - numpy>=1.15.0
    - scipy
    - pandas
    - pyyaml
    - pytables
  run:
    - python>=3.9
    - matplotlib
    - numpy>=1.15.0
    - scipy
    - pandas
    - pyyaml
    - pytables
  test:
    imports:
      - likelihood_combiner

about:
  home: https://github.com/TjarkMiener/likelihood_combiner
  license: GPL-3.0 License
  license_file: LICENSE
  summary: LikelihoodCombiner combines likelihoods from different experiments.
extra:
  recipe-maintainers:
    - TjarkMiener
    - nietootein
