Hardware:
  cpu_counts: 30
Data:
  data_directory: /Users/tmiener/Desktop/likelihood_combiner/data/
  simulations: 30
  j_nuisance: true
  j_factors: 'GeringerSameth'
  # Define the sigma ranges
  sigmaV_min: 1e-28
  sigmaV_max: 1e-18
  sigmaV_nPoints: 1001
Configuration:
  channels: ['bb', 'mumu', 'tautau', 'WW']
  sources: ['Segue1', 'UrsaMajorII']
  collaborations: {'IACT': 2.6}
Output:
  output_directory: /Users/tmiener/Desktop/likelihood_combiner/output/
  hdf5_dataset: lklcom.h5
  collaboration_plot: false
