Hardware:
  cpu_counts: 30
Data:
  data_directory: /Users/tmiener/Documents/likelihood_combiner/data/
  cl_bands: true
  simulations: 30
  J_nuisance: true
  JFactor_table: /Users/tmiener/Documents/likelihood_combiner/data/Jfactor_Geringer-SamethTable.txt
  # Define the sigma ranges
  sigmaV_min: 1e-28
  sigmaV_max: 1e-18
  sigmaV_nPoints: 1001
Configuration:
  channels: ['bb', 'mumu', 'tautau', 'WW']
  sources: ['Segue1', 'UrsaMajorII']
  collaborations: ['IACT']
Output:
  output_directory: /Users/tmiener/Documents/likelihood_combiner/output/
  hdf5_dataset: lklcom.h5
  collaboration_plot: false
