Hardware:
  cpu_counts: 31
Data:
  buildin_j_factors: 'GeringerSameth'
  custom_logJ: {"Segue1": {"IACT": 19.25}}
  custom_DlogJ: {"Segue1": {"IACT": 0.25}}
  j_nuisance: True
  simulations: 30
  # Define the sigmav range
  #sigmav_min: 1e-28
  #sigmav_max: 1e-18
  #sigmav_nPoints: 1001
Configuration:
  channels: ['bb']
  #channels: ['bb', 'mumu', 'tautau', 'WW']
  sources: ['Segue1', 'UrsaMajorII']
  collaborations: {'IACT': 2.6}
