Hardware:
  cpu_counts: 31
Data:
  input: '/Users/tmiener/deeplearning/likelihood_combiner/resources/mock_data.hdf5'
  #input: '/Users/tmiener/deeplearning/likelihood_combiner/resources/mock_txt_data/'
  buildin_j_factors: 'GeringerSameth'
  resources: '/Users/tmiener/deeplearning/likelihood_combiner/resources/'
  custom_logJ: {"Segue1": {"IACT": 19.25}}
  custom_DlogJ: {"Segue1": {"IACT": 0.25}}
  j_nuisance: True
  simulations: 30
  # Define the sigmav range
  #sigmav_min: 1e-28
  #sigmav_max: 1e-18
  #sigmav_nPoints: 1001
Configuration:
  channels: ['bb', 'mumu', 'tautau', 'WW']
  sources: ['Segue1', 'UrsaMajorII']
  collaborations: {'IACT': 2.6}
Output:
  directory: "/Users/tmiener/deeplearning/likelihood_combiner/output/"
  file: "/Users/tmiener/deeplearning/likelihood_combiner/output/test_output_hdf5.hdf5"
